/**
 * TypeScript types for Lastensuojelu (Child Welfare) Portal
 * Generated from Aineisto markdown files
 */

// ============================================================================
// LS-ilmoitus (Child Welfare Notification)
// ============================================================================

export interface LSNotification {
  id: string;
  date: string; // ISO date string
  filename: string;
  reporter: {
    name: string;
    profession: string;
    address?: string;
    phone?: string;
    email?: string;
    isOfficial: boolean; // Onko viranomainen
  };
  child: {
    name: string;
    socialSecurityNumber: string;
    address: string;
    school?: string;
  };
  guardians: {
    mother?: {
      name: string;
      socialSecurityNumber?: string;
      address?: string;
      phone?: string;
      email?: string;
    };
    father?: {
      name: string;
      socialSecurityNumber?: string;
      address?: string;
      phone?: string;
      email?: string;
    };
  };
  reason: string; // Main reason/description
  highlights: string[]; // Key concerns highlighted in original doc
  summary: string; // Short summary for list view (generated by LLM)
  fullText: string; // Complete markdown content
  // LLM-generated fields
  generatedDate?: string; // Luomispäivämäärä from LLM (YYYY-MM-DD)
  urgency?: 'kriittinen' | 'kiireellinen' | 'normaali' | 'ei_kiireellinen'; // lastensuojelutarpeen kiireellisyys
}

// ============================================================================
// Asiakaskirjaukset (Case Notes)
// ============================================================================

export interface CaseNote {
  id: string;
  date: string; // ISO date string
  keywords: string[]; // e.g., ['alkoholi', 'karannut', 'poliisi']
  notificationGround: string; // ilmoitusperuste category
  fullText: string;
}

// ============================================================================
// PTA kirjaukset (Service Plan Records)
// ============================================================================

export interface PTARecord {
  id: string;
  date: string; // ISO date string
  filename?: string; // Original filename in storage
  eventType: 'kotikäynti' | 'puhelu' | 'tapaaminen' | 'neuvottelu' | 'päätös' | 'muu';
  participants: string[]; // e.g., ['isä', 'sosiaaliohjaaja']
  summary: string; // Brief summary
  actions: string[]; // Actions taken
  aiGuidance?: string; // AI guidance if present
  fullText: string;
  colorCoding?: {
    symptoms?: string[]; // Pink highlights
    actions?: string[]; // Green highlights
    aiGuidance?: string[]; // Yellow highlights
  };
  // PTA-specific fields (from Firestore)
  sections?: Record<string, string>; // All document sections
  palvelut?: string[]; // Services provided
  highlights?: string[]; // Key highlights from document
}

// ============================================================================
// Päätökset (Decisions)
// ============================================================================

export interface Decision {
  id: string;
  date: string; // ISO date string
  filename?: string; // Original filename in storage
  decisionType:
    | 'asiakkuuden_avaaminen'      // Asiakkuus alkaa
    | 'asiakkuuden_paattyminen'    // Asiakkuus päättyy
    | 'selvitys_aloitetaan'        // Selvitys käynnistyy
    | 'kiireellinen_sijoitus'
    | 'avohuollon_tukitoimi'
    | 'muu';
  summary: string;
  legalBasis: string; // e.g., "Lastensuojelulaki § 38"
  highlights?: string[];  // Korostetut kohdat ([oleellinen], [päätös peruste])
  fullText: string;
}

// ============================================================================
// Yhteystiedot (Contact Information)
// ============================================================================

export interface ContactInfo {
  child: {
    name: string;
    socialSecurityNumber: string;
    address: string;
    school?: string;
  };
  guardians: {
    mother?: {
      name: string;
      socialSecurityNumber?: string;
      address?: string;
      phone?: string;
      email?: string;
    };
    father?: {
      name: string;
      socialSecurityNumber?: string;
      address?: string;
      phone?: string;
      email?: string;
    };
  };
  reporters: Array<{
    name: string;
    profession: string;
    phone?: string;
    email?: string;
    workplace?: string;
  }>;
  professionals: {
    socialWorker?: {
      name: string;
      phone?: string;
      email?: string;
    };
    socialGuide?: {
      name: string;
      phone?: string;
      email?: string;
    };
    teacher?: {
      name: string;
      phone?: string;
      email?: string;
      school?: string;
    };
  };
}

// ============================================================================
// Asiakassuunnitelma (Service Plan)
// ============================================================================

export interface ServicePlan {
  id: string;
  serviceType: string; // e.g., 'perhetyö', 'viikoittaiset tapaamiset'
  startDate: string;
  endDate?: string;
  status: 'active' | 'completed' | 'cancelled';
  description: string;
  goals?: string[];
  outcomes?: string;
}

// ============================================================================
// Main Problem / Paaongelma
// ============================================================================

export interface MainProblem {
  category: string; // e.g., 'lapsen psyykkinen vointi'
  subcategories: string[]; // e.g., ['päihteiden käyttö', 'perheväkivalta']
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
}

// ============================================================================
// Organization and User Roles
// ============================================================================

export interface UserRole {
  userId: string;
  userEmail: string;
  role: 'oma_työntekijä' | 'vastuullinen_sosiaalityöntekijä' | 'sosiaalipalvelun_esimies';
}

export interface ClientOrganization {
  clientId: string; // Technical key (UUID)
  clientName: string;
  socialSecurityNumber?: string; // SOTU (optional, sensitive data)
  roles: UserRole[];
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================================
// Complete Client Data (Multi-client support)
// ============================================================================

export interface LSClientData {
  clientId: string; // Technical key (UUID)
  clientName: string;
  socialSecurityNumber?: string; // SOTU (optional)
  organization: ClientOrganization;
  mainProblem: MainProblem;
  notifications: LSNotification[];
  caseNotes: CaseNote[];
  decisions: Decision[];
  contactInfo: ContactInfo;
  ptaRecords: PTARecord[];
  servicePlans: ServicePlan[];
  timeline: TimelineEvent[]; // Chronological view of all events
}

// ============================================================================
// Timeline Event (for chronological view)
// ============================================================================

export interface TimelineEvent {
  id: string;
  date: string;
  type: 'notification' | 'case_note' | 'decision' | 'pta_record' | 'service_plan';
  title: string;
  summary: string;
  relatedId: string; // ID of the related notification, case note, etc.
}

// ============================================================================
// Summary Data for UI Components
// ============================================================================

export interface LSSummaries {
  notificationsSummary: Array<{
    date: string;
    reporter: string;
    mainConcern: string;
  }>;
  recentCaseNotes: Array<{
    date: string;
    ground: string;
    keywords: string[];
  }>;
  activeServicePlans: Array<{
    service: string;
    startDate: string;
    status: string;
  }>;
  decisionsSummary: Array<{
    date: string;
    type: string;
    summary: string;
  }>;
}
